fix: formatting, linting, and schema code generation
CHANGELOG:
- [ ] Addresses error handling and parallelized formatting for toml
  files.
- [ ] Configures the ruff formatter to use requested format.
- [ ] Fixes snake_case for several Python variables.
- [ ] Configures the schemas.py code generator to generate snake_case
  field names to avoid lint reports and wraps the actual name in Field()
  metadata.
- [ ] Clean up some lint.

diff --git a/py/bin/format_toml_files b/py/bin/format_toml_files
--- a/py/bin/format_toml_files
+++ b/py/bin/format_toml_files
@@ -9,52 +9,63 @@ set -euo pipefail
 
 GIT_ROOT=$(git rev-parse --show-toplevel)
 
-if command -v rust-parallel >/dev/null 2>&1; then
+if command -v taplo >/dev/null 2>&1; then
+  if [ ! -f "${GIT_ROOT}/py/taplo.toml" ]; then
+    echo "error: config file not found at ${GIT_ROOT}/py/taplo.toml"
+    exit 1
+  fi
+
+  FORMATTER_COMMAND="taplo format --config ${GIT_ROOT}/py/taplo.toml"
+  if command -v rust-parallel >/dev/null 2>&1; then
+    FORMATTER_COMMAND="rust-parallel -j4 ${FORMATTER_COMMAND}"
+  fi
+
   if command -v fd >/dev/null 2>&1; then
+    echo "Using fd"
     fd -e toml \
-      --exclude 'py/**/*.egg-info/**' \
-      --exclude 'py/**/.dist/**' \
-      --exclude 'py/**/.next/**' \
-      --exclude 'py/**/.output/**' \
-      --exclude 'py/**/.pytest_cache/**' \
-      --exclude 'py/**/.venv/**' \
-      --exclude 'py/**/__pycache__/**' \
-      --exclude 'py/**/build/**' \
-      --exclude 'py/**/develop-eggs/**' \
-      --exclude 'py/**/dist/**' \
-      --exclude 'py/**/eggs/**' \
-      --exclude 'py/**/node_modules/**' \
-      --exclude 'py/**/sdist/**' \
-      --exclude 'py/**/site/**' \
-      --exclude 'py/**/target/**' \
-      --exclude 'py/**/venv/**' \
-      --exclude 'py/**/wheels/**' |
-      rust-parallel -j4 \
-        taplo format --config "${GIT_ROOT}/py/taplo.toml"
+      --exclude '**/*.egg-info/**' \
+      --exclude '**/.dist/**' \
+      --exclude '**/.next/**' \
+      --exclude '**/.output/**' \
+      --exclude '**/.pytest_cache/**' \
+      --exclude '**/.venv/**' \
+      --exclude '**/__pycache__/**' \
+      --exclude '**/bazel-*/**' \
+      --exclude '**/build/**' \
+      --exclude '**/develop-eggs/**' \
+      --exclude '**/dist/**' \
+      --exclude '**/eggs/**' \
+      --exclude '**/node_modules/**' \
+      --exclude '**/sdist/**' \
+      --exclude '**/site/**' \
+      --exclude '**/target/**' \
+      --exclude '**/venv/**' \
+      --exclude '**/wheels/**' |
+      ${FORMATTER_COMMAND}
   else
     echo "Using find"
     find "${GIT_ROOT}" -name "*.toml" \
-      ! -path 'py/**/*.egg-info/**' \
-      ! -path 'py/**/.dist/**' \
-      ! -path 'py/**/.next/**' \
-      ! -path 'py/**/.output/**' \
-      ! -path 'py/**/.pytest_cache/**' \
-      ! -path 'py/**/.venv/**' \
-      ! -path 'py/**/__pycache__/**' \
-      ! -path 'py/**/build/**' \
-      ! -path 'py/**/develop-eggs/**' \
-      ! -path 'py/**/dist/**' \
-      ! -path 'py/**/eggs/**' \
-      ! -path 'py/**/node_modules/**' \
-      ! -path 'py/**/sdist/**' \
-      ! -path 'py/**/site/**' \
-      ! -path 'py/**/target/**' \
-      ! -path 'py/**/venv/**' \
-      ! -path 'py/**/wheels/**' \
+      ! -path '**/*.egg-info/**' \
+      ! -path '**/.dist/**' \
+      ! -path '**/.next/**' \
+      ! -path '**/.output/**' \
+      ! -path '**/.pytest_cache/**' \
+      ! -path '**/.venv/**' \
+      ! -path '**/__pycache__/**' \
+      ! -path '**/bazel-*/**' \
+      ! -path '**/build/**' \
+      ! -path '**/develop-eggs/**' \
+      ! -path '**/dist/**' \
+      ! -path '**/eggs/**' \
+      ! -path '**/node_modules/**' \
+      ! -path '**/sdist/**' \
+      ! -path '**/site/**' \
+      ! -path '**/target/**' \
+      ! -path '**/venv/**' \
+      ! -path '**/wheels/**' \
       -print0 |
-      rust-parallel -j4 \
-        taplo format --config "${GIT_ROOT}/py/taplo.toml"
+      ${FORMATTER_COMMAND}
   fi
 else
-  echo "Please install GNU parallel to use this script"
+  echo "Please install taplo to use this script"
 fi
